version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: ludo_postgres:latest
    build: ./postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
  base:
    image: ludo_base:latest
    build: ./base
    profiles:
      - base
  builder:
    image: ludo_builder:latest
    build:
      context: .
      dockerfile: builder/Dockerfile
    profiles:
      - builder
  game_server:
    image: ludo_game_server:latest
    build: ./game-server
    restart: on-failure
    env_file: .env
    environment:
      SPRING_APPLICATION_JSON:
        '{
          "server.port" : "${SB_PORT}",
          "spring.datasource.url" : "jdbc:postgresql://postgres/${POSTGRES_DB}",
          "spring.datasource.username" : "${POSTGRES_USER}",
          "spring.datasource.password" : "${POSTGRES_PASSWORD}"
        }'
    ports:
      - "${SB_PORT}:${SB_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
