logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
  group:
    security:
     - org.springframework.security
     - org.springframework.security.oauth2
     - org.springframework.boot.autoconfigure.security
  level:
    root: INFO
    web: INFO
    security: INFO
    hu.bme.aut.alkfejl.ludospringboot: DEBUG
    org.springframework.security.web.DefaultSecurityFilterChain: WARN

spring:
  application:
    name: game-server
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    show-sql: false
  output.ansi.enabled: detect
